name: CI

on:
  push:
    branches:
      - main
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      -
        id: install
        name: Install
        run: |
          make install

      -
        id: vet
        name: Vet
        run: |
          make check/vet

      -
        id: fmt
        name: Check Format
        run: |
          make check/fmt

      -
        id: Test
        name: Test
        run: |
          make test

      -
        id: Build
        name: Build
        run: |
          make build
