name: CI

on:
  push:
    branches:
      - main
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  checks:
    name: Checks
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      -
        id: install
        name: Install
        run: |
          make install

      -
        id: Test
        name: Test
        run: |
          make test
